<?php
/**
 * @file
 * The main code for KP Frontpage.
 */


/**
 * Implements hook_preprocess_page().
 */
function kptheme_preprocess_page(&$vars, $hook) {
  if (drupal_is_front_page()) {
    // Embed style and JS file only when it is the frontpage.
    $path = drupal_get_path('module', 'kp_frontpage');
    drupal_add_css($path . '/kp_frontpage.css');
    drupal_add_js ($path . '/js/kp_frontpage.js', array('scope' => 'footer'));

    $vars['path_images'] = $path . '/images/';

    // Stats about data.
    $sql = "SELECT * FROM {kp_frontpage_stats}";
    $result = chado_query($sql);
    $arr_stats_bar = array();

    foreach($result as $stat) {
      // Bar chart.
      $arr_stats_bar[$stat->type] = array(
        'short_value' => kp_frontpage_shortval($stat->count),
        'long_value'  => number_format($stat->count),
      );
    }

    $vars['data_stats'] = $arr_stats_bar;
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 * Credits: https://www.drupal.org/forum/support/post-installation/2011-01-26/turn-off-contextual-links-in-d7.
 */
function kp_frontpage_contextual_links_view_alter(&$element, $items) {
  // Disable contextual links on views as it messes up markup.
  // For example: the link uses ul in the news section which uses ul as well
  // and trying to find the actual number of li in news includes the li in contextual links.
  if (isset($element['#element']['#views_contextual_links_info'])) {
    unset($element['#links']);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function kp_frontpage_theme_registry_alter(&$theme_registry) {

  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'kp_frontpage') . '/templates';

  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {

    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implementation of hook_views_api()
 */
function kp_frontpage_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_node_info().
 */
function kp_frontpage_node_info() {

  $content_type = array(
    // Machine name.
    'kp_frontpage_cms' => array(
      // Human-readable name.
      'name' => t('KP Frontpage Content'),
      // Description.
      'description' => t('Manage KP frontpage content.'),
      // Title.
      'has_title' => TRUE,
      'title_label' => t('Content Title:'),
      // Base name for implementation. Usually the module name.
      'base' => 'kp_frontpage',
      // Disable option to let administrators change the machine
      // name of this content type.
      'locked' => TRUE,
    )
  );

  return $content_type;
}

/**
 * Implements hook_form().
 */
function kp_frontpage_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Shortens a number in K/M/B.
 *
 * @param $value
 *   An integer containing the number to be formatted.
 *
 * @return string
 *   Shortened result.
 */
function kp_frontpage_shortval($value) {
  if ($value < 1000) {
    // Hundred and less.
    $value = $value;
  }
  else if ($value < 1000000) {
    // Thousand.
    $value = round($value / 1000, 0) . 'K';
  }
  else if ($value < 1000000000) {
    // Million.
    $value = round($value / 1000000, 0) . 'M';
  }
  else {
    // Billion.
    $value = round($value / 1000000000, 0) . 'B';
  }

  return $value;
}
